# Constants
FPS = 30
WINDOWWIDTH = 700
WINDOWHEIGHT = 550
FLASHSPEED = 500
FLASHDELAY = 200
BUTTONSIZE = 200
BUTTONGAPSIZE = 20

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BRIGHTRED = (255, 0, 0)
RED = (155, 0, 0)
BRIGHTGREEN = (0, 255, 0)
GREEN = (0, 155, 0)
BRIGHTBLUE = (0, 0, 255)
BLUE = (0, 0, 155)
BRIGHTYELLOW = (255, 255, 0)
YELLOW = (155, 155, 0)
BRIGHTORANGE = (255, 140, 0)
ORANGE = (175, 60, 0)
BRIGHTPURPLE = (128, 0, 128)
PURPLE = (68, 0, 68)

bgColor = BLACK
XMARGIN = int((WINDOWWIDTH - (3 * BUTTONSIZE) - 2 * BUTTONGAPSIZE) / 2)
YMARGIN = 50

# Mappings
COLOR_KEY_MAP = {
    YELLOW: 'Q',
    BLUE: 'W',
    RED: 'E',
    GREEN: 'A',
    ORANGE: 'S',
    PURPLE: 'D'
}
COLOR_BRIGHT_MAP = {
    YELLOW: BRIGHTYELLOW,
    BLUE: BRIGHTBLUE,
    RED: BRIGHTRED,
    GREEN: BRIGHTGREEN,
    ORANGE: BRIGHTORANGE,
    PURPLE: BRIGHTPURPLE
}
import pygame
RECT_MAP = {
    YELLOW: pygame.Rect(XMARGIN, YMARGIN, BUTTONSIZE, BUTTONSIZE),
    BLUE: pygame.Rect(XMARGIN + BUTTONSIZE + BUTTONGAPSIZE, YMARGIN, BUTTONSIZE, BUTTONSIZE),
    RED: pygame.Rect(XMARGIN + 2 * (BUTTONSIZE + BUTTONGAPSIZE), YMARGIN, BUTTONSIZE, BUTTONSIZE),
    GREEN: pygame.Rect(XMARGIN, YMARGIN + BUTTONSIZE + BUTTONGAPSIZE, BUTTONSIZE, BUTTONSIZE),
    ORANGE: pygame.Rect(XMARGIN + BUTTONSIZE + BUTTONGAPSIZE, YMARGIN + BUTTONSIZE + BUTTONGAPSIZE, BUTTONSIZE, BUTTONSIZE),
    PURPLE: pygame.Rect(XMARGIN + 2 * (BUTTONSIZE + BUTTONGAPSIZE), YMARGIN + BUTTONSIZE + BUTTONGAPSIZE, BUTTONSIZE, BUTTONSIZE)
}
